platform :ios, '26.0'
use_frameworks!

target 'TheMovie' do
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire', '~> 5.8'
  pod 'SkeletonView', '~> 1.30'
  pod 'Hero', '~> 1.6'
end

target 'TheMovieTests' do
  inherit! :search_paths
  pod 'Nimble', '~> 13.0'
  pod 'Quick', '~> 7.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SkeletonView', '~> 1.30'
  pod 'Hero', '~> 1.6'
end

def sync_tmdb_config
  placeholder = 'your_tmdb_read_access_token_here'
  token = placeholder
  env_path = File.join(__dir__, '.env')

  if File.exist?(env_path)
    File.readlines(env_path).each do |line|
      next if line.strip.start_with?('#') || line.strip.empty?

      key, value = line.strip.split('=', 2)
      next unless key == 'TMDB_BEARER_TOKEN' && value

      token = value.strip.delete('"').delete("'")
    end
  elsif File.exist?(File.join(__dir__, 'Config.xcconfig'))
    File.readlines(File.join(__dir__, 'Config.xcconfig')).each do |line|
      next unless line.include?('TMDB_BEARER_TOKEN')

      token = line.split('=', 2)[1].to_s.strip
    end
  end

  config_path = File.join(__dir__, 'Config.xcconfig')
  File.write(
    config_path,
    <<~CONFIG
      // Generated by CocoaPods from .env — do not commit.
      TMDB_BEARER_TOKEN = #{token}
    CONFIG
  )
  puts "Synced TMDB token to Config.xcconfig"
end

post_install do |installer|
  sync_tmdb_config

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.save
  end

  pods_the_movie = Dir.glob('Pods/Target Support Files/Pods-TheMovie/Pods-TheMovie.*.xcconfig')
  pods_the_movie.each do |path|
    contents = File.read(path)
    include_line = '#include? "../../../Config.xcconfig"'
    next if contents.include?(include_line)
    File.write(path, "#{include_line}\n#{contents}")
  end
end
